version: '3.8'

services:

  nginx:
    container_name: nginxsol
    image: nginx:alpine
    ports:
      - "0.0.0.0:8080:80"
    depends_on:
      - app
      - db
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
  db:
    image: postgres
    container_name: pgsqlsol
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 190600
      POSTGRES_DB: soluminarbk

  app:
    container_name: soluminar
    build:
      context: ./php
      dockerfile: Dockerfile

    volumes:
      - ./src:/var/www
    ports:
      - "0.0.0.0:9000:9000"
    working_dir: /var/www




